/**
 * Stroke Processor WASM Integration
 *
 * Provides TypeScript interface to the Rust WASM stroke tessellation module.
 */

import type { Annotation, AnnotationPoint } from '../types';

// WASM module interface (generated by wasm-bindgen)
interface StrokeProcessorWasm {
  tessellate_variable_stroke(
    points: Float32Array,
    color: Float32Array,
    tolerance: number
  ): TessellatedStrokeWasm;

  tessellate_stroke(
    points: Float32Array,
    strokeWidth: number,
    color: Float32Array,
    tolerance: number
  ): TessellatedStrokeWasm;

  tessellate_fill(
    points: Float32Array,
    color: Float32Array,
    tolerance: number
  ): TessellatedStrokeWasm;

  simplify_path(points: Float32Array, epsilon: number): Float32Array;

  calculate_bounds(points: Float32Array, pointStride: number): Float32Array;
}

interface TessellatedStrokeWasm {
  vertices: Float32Array;
  indices: Uint32Array;
  vertex_count: number;
  index_count: number;
  free(): void;
}

// TypeScript result interface
export interface TessellatedStroke {
  vertices: Float32Array;
  indices: Uint32Array;
  vertexCount: number;
  indexCount: number;
}

// WASM module state
let wasmModule: StrokeProcessorWasm | null = null;
let wasmLoading: Promise<void> | null = null;

/**
 * Initialize WASM module
 */
export async function initWasm(): Promise<void> {
  if (wasmModule) return;

  if (wasmLoading) {
    return wasmLoading;
  }

  wasmLoading = (async () => {
    // Skip in SSR
    if (typeof window === 'undefined') return;

    const module = await import('./stroke_processor_wasm.js');
    if (module.default) {
      await module.default();
    }
    wasmModule = module as unknown as StrokeProcessorWasm;
    console.log('WASM stroke processor initialized');
  })();

  return wasmLoading;
}

/**
 * Get WASM module (throws if not initialized)
 */
function getWasm(): StrokeProcessorWasm {
  if (!wasmModule) {
    throw new Error('WASM not initialized. Call initWasm() first.');
  }
  return wasmModule;
}

/**
 * Convert hex color to RGBA array
 */
function hexToRgba(hex: string, alpha: number = 1.0): Float32Array {
  const result = new Float32Array(4);
  hex = hex.replace('#', '');

  if (hex.length === 3) {
    hex = hex[0] + hex[0] + hex[1] + hex[1] + hex[2] + hex[2];
  }

  result[0] = parseInt(hex.substring(0, 2), 16) / 255;
  result[1] = parseInt(hex.substring(2, 4), 16) / 255;
  result[2] = parseInt(hex.substring(4, 6), 16) / 255;
  result[3] = alpha;

  return result;
}

/**
 * Flatten annotation points to typed array for variable width strokes
 * Format: [x0, y0, w0, x1, y1, w1, ...]
 */
function flattenPointsWithWidth(points: AnnotationPoint[], defaultWidth: number): Float32Array {
  const arr = new Float32Array(points.length * 3);
  for (let i = 0; i < points.length; i++) {
    arr[i * 3] = points[i].x;
    arr[i * 3 + 1] = points[i].y;
    arr[i * 3 + 2] = points[i].width ?? defaultWidth;
  }
  return arr;
}

/**
 * Flatten annotation points to typed array for uniform width strokes
 * Format: [x0, y0, x1, y1, ...]
 */
function flattenPoints(points: AnnotationPoint[]): Float32Array {
  const arr = new Float32Array(points.length * 2);
  for (let i = 0; i < points.length; i++) {
    arr[i * 2] = points[i].x;
    arr[i * 2 + 1] = points[i].y;
  }
  return arr;
}

/**
 * Tessellate a variable-width stroke (brush)
 */
export function tessellateVariableStroke(
  annotation: Annotation,
  tolerance: number = 0.5
): TessellatedStroke | null {
  if (annotation.points.length < 2) return null;

  const wasm = getWasm();
  const points = flattenPointsWithWidth(annotation.points, annotation.strokeWidth);
  const color = hexToRgba(annotation.color);

  const result = wasm.tessellate_variable_stroke(points, color, tolerance);
  const tessellated: TessellatedStroke = {
    vertices: new Float32Array(result.vertices),
    indices: new Uint32Array(result.indices),
    vertexCount: result.vertex_count,
    indexCount: result.index_count
  };
  result.free();
  return tessellated;
}

/**
 * Tessellate a uniform-width stroke (pen)
 */
export function tessellateStroke(
  annotation: Annotation,
  tolerance: number = 0.5
): TessellatedStroke | null {
  if (annotation.points.length < 2) return null;

  const wasm = getWasm();
  const points = flattenPoints(annotation.points);
  const color = hexToRgba(annotation.color);

  const result = wasm.tessellate_stroke(points, annotation.strokeWidth, color, tolerance);
  const tessellated: TessellatedStroke = {
    vertices: new Float32Array(result.vertices),
    indices: new Uint32Array(result.indices),
    vertexCount: result.vertex_count,
    indexCount: result.index_count
  };
  result.free();
  return tessellated;
}

/**
 * Simplify path using RDP algorithm
 */
export function simplifyPath(
  points: AnnotationPoint[],
  epsilon: number
): AnnotationPoint[] {
  if (points.length <= 2) return points;

  const wasm = getWasm();
  const flatPoints = flattenPoints(points);
  const simplified = wasm.simplify_path(flatPoints, epsilon);

  const result: AnnotationPoint[] = [];
  for (let i = 0; i < simplified.length; i += 2) {
    // Find original point to preserve width
    const originalIdx = points.findIndex(
      p => Math.abs(p.x - simplified[i]) < 0.01 && Math.abs(p.y - simplified[i + 1]) < 0.01
    );
    if (originalIdx >= 0) {
      result.push(points[originalIdx]);
    } else {
      result.push({ x: simplified[i], y: simplified[i + 1] });
    }
  }
  return result;
}

/**
 * Calculate bounding box for points
 */
export function calculateBounds(
  points: AnnotationPoint[],
  padding: number = 0
): { minX: number; minY: number; maxX: number; maxY: number } {
  if (points.length === 0) {
    return { minX: 0, minY: 0, maxX: 0, maxY: 0 };
  }

  const wasm = getWasm();
  const flatPoints = flattenPoints(points);
  const bounds = wasm.calculate_bounds(flatPoints, 2);

  return {
    minX: bounds[0] - padding,
    minY: bounds[1] - padding,
    maxX: bounds[2] + padding,
    maxY: bounds[3] + padding
  };
}
